# -*- coding: utf-8 -*-
"""Projectwork15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqFM3q14VQ8zawt70-QMvEJ5yaCHLUFN
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

# Nome del file generato dalla simulazione precedente
NOME_FILE_CSV = "export_dati_produzione_v2.csv"

def genera_grafico_finale(csv_path, output_image="grafico_performance_color.png"):
    """
    Funzione che legge i dati della simulazione e genera un report grafico.
    """

    # 1. CONTROLLO INTEGRITÀ FILE
    # Verifica che il file CSV esista nel percorso specificato prima di procedere.
    # Questo evita crash improvvisi se ci si sposta tra ambienti diversi (es. Colab/Locale).
    if not os.path.exists(csv_path):
        print(f"⚠️ AVVISO: Il file '{csv_path}' non è stato trovato.")
        print("SUGGERIMENTO: Assicurati di aver eseguito prima lo script di simulazione per generare i dati.")
        return

    # 2. CARICAMENTO DATI
    # Utilizziamo un blocco try-except per gestire eventuali errori di formattazione nel CSV.
    try:
        # Il separatore è ';' come definito nella fase di export
        df = pd.read_csv(csv_path, sep=';')
    except Exception as e:
        print(f"Errore durante la lettura del CSV: {e}")
        return

    # 3. ELABORAZIONE DATI (Data Aggregation)
    # Raggruppiamo i dati per 'Coltura' sommando i volumi (Kg) e le ore lavorative.
    # Questo passaggio trasforma i dati grezzi in KPI utili per il grafico.
    df_agg = df.groupby('Coltura').agg({
        'Input_Totale_Kg': 'sum',
        'Ore_Seq_A': 'sum',
        'Ore_Seq_B': 'sum'
    }).reset_index()

    # 4. LOGICA CONDIZIONALE PER I COLORI
    # Assegniamo colori specifici per rendere il grafico intuitivo:
    # Arancione -> Arance, Verde -> Olive, Rosa -> Pesche.
    colori_barre = []
    for nome in df_agg['Coltura']:
        n = nome.lower()
        if 'aranc' in n:
            colori_barre.append('#ff8c00')  # Arancione scuro
        elif 'oliv' in n:
            colori_barre.append('#556b2f')  # Verde oliva
        elif 'pesc' in n:
            colori_barre.append('#ff9999')  # Rosa pesca
        else:
            colori_barre.append('gray')     # Colore di default

    # 5. CONFIGURAZIONE LAYOUT GRAFICO
    # Creiamo una figura con due sottografici (subplots) affiancati.
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))
    plt.subplots_adjust(wspace=0.25) # Spazio bianco tra i grafici

    # --- GRAFICO SINISTRO: VOLUMI DI PRODUZIONE ---
    bars = ax1.bar(df_agg['Coltura'], df_agg['Input_Totale_Kg'], color=colori_barre, edgecolor='black', alpha=0.9)

    ax1.set_title('Volume Produzione Stimata (Kg)', fontsize=14, fontweight='bold', pad=15)
    ax1.set_ylabel('Quantità (Kg)', fontsize=12)
    ax1.grid(axis='y', linestyle='--', alpha=0.4) # Griglia orizzontale leggera

    # Annotazione valori (Data Labels) sopra le barre
    for bar in bars:
        height = bar.get_height()
        ax1.text(bar.get_x() + bar.get_width()/2., height + 50,
                 f'{int(height)} kg', ha='center', va='bottom', fontweight='bold')

    # --- GRAFICO DESTRO: ANALISI ORE LAVORO (Stacked Bar) ---
    x = np.arange(len(df_agg['Coltura']))
    width = 0.5

    # Creiamo un grafico a barre impilate (Stacked Bar Chart) per confrontare le fasi.
    # Fase A (Preparazione/Manuale) in Blu
    p1 = ax2.bar(x, df_agg['Ore_Seq_A'], width, label='Fase A (Prep./Manuale)', color='#4682B4', edgecolor='black')
    # Fase B (Industria/Meccanica) in Rosso, posizionata sopra la Fase A (bottom=...)
    p2 = ax2.bar(x, df_agg['Ore_Seq_B'], width, bottom=df_agg['Ore_Seq_A'], label='Fase B (Ind./Meccanica)', color='#CD5C5C', edgecolor='black')

    ax2.set_title('Fabbisogno Ore: Sequenza A vs B', fontsize=14, fontweight='bold', pad=15)
    ax2.set_ylabel('Ore Totali', fontsize=12)
    ax2.set_xticks(x)
    ax2.set_xticklabels(df_agg['Coltura'], rotation=10, fontsize=10) # Rotazione etichette per leggibilità
    ax2.legend(loc='upper left')
    ax2.grid(axis='y', linestyle='--', alpha=0.4)

    # Etichette col totale delle ore in cima alla barra
    for i in range(len(df_agg)):
        tot = df_agg['Ore_Seq_A'][i] + df_agg['Ore_Seq_B'][i]
        ax2.text(i, tot + 2, f'{int(tot)} h', ha='center', va='bottom', fontweight='bold')

    # 6. SALVATAGGIO E VISUALIZZAZIONE
    plt.tight_layout() # Ottimizza gli spazi automaticamente
    plt.savefig(output_image, dpi=150) # Salva in alta risoluzione
    print(f"✅ Grafico generato con successo: {output_image}")
    plt.show()

if __name__ == "__main__":
    genera_grafico_finale(NOME_FILE_CSV)